#5 init
alekceev/gb-go1 pull request #5
Opened 2021-12-06 16:40 UTC by alekceev

заглушка, сделаю позже

2021-12-06 21:17 UTC, alekceev commented
сделал

2021-12-07 20:14 UTC, v-lozhkin requested changes

2021-12-07 20:14 UTC, v-lozhkin commented on homework5/1_fibo/main.go
> +	fibo := func() func() int {
В целом, работоает, но в задании явно указано требование к тому, чтобы вычислять число рекурсивно

2021-12-08 06:21 UTC, alekceev commented on homework5/1_fibo/main.go
> +	fibo := func() func() int {
переделал

2021-12-08 07:24 UTC, v-lozhkin commented on homework5/2_fibo/main.go
> +		cache["first"], cache["second"] = cache["second"], cache["first"]+cache["second"]
Весьма нестандартное решение. 
Принято

2021-12-08 07:25 UTC, v-lozhkin approved these changes

2021-12-08 07:49 UTC, merged